# Generated by Django 5.1.1 on 2024-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
