# Generated by Django 5.1.1 on 2024-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0002_invoice_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
