# Generated by Django 5.1.1 on 2024-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0003_alter_invoiceitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
