# Generated by Django 5.1.1 on 2024-09-23 20:56

import autoslug.fields
import dirtyfields.dirtyfields
import django.db.models.deletion
import invoiceio.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0004_alter_invoiceitem_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=invoiceio.utils.get_invoice_item_connector_slug, unique=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceio.invoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceio.invoiceitem')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
