# Generated by Django 5.1.1 on 2024-09-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0005_invoiceitemconnector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_item',
        ),
    ]
