# Generated by Django 5.1.1 on 2024-09-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0006_remove_invoice_invoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
