# Generated by Django 5.1.1 on 2024-09-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0007_remove_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
