# Generated by Django 5.1.1 on 2024-09-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0008_invoice_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
