# Generated by Django 5.1.1 on 2024-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0010_remove_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Un Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial')], default='UNPAID', max_length=20),
        ),
    ]
