# Generated by Django 5.1.1 on 2024-09-24 14:58

import invoiceio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceio', '0011_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoiceio.utils.get_invoice_media_path_prefix),
        ),
    ]
