# Generated by Django 5.1.1 on 2024-09-23 15:39

import autoslug.fields
import dirtyfields.dirtyfields
import productio.utils
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=productio.utils.get_product_slug, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('PENDING', 'Pending')], default='DRAFT', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.FloatField(help_text='here will be perchantage of discount')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=productio.utils.get_product_media_path_prefix, verbose_name='Image')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
